USE [CDCDB]
GO

 IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'User')
 BEGIN
  PRINT 'CREATING USER TABLE...'
  CREATE TABLE [USER](
   [UserId] INT IDENTITY(1,1) NOT NULL,
   [FirstName] NVARCHAR(50) NOT NULL,
   [LastName] NVARCHAR(50) NOT NULL)
 END